@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package jakojaannos.life.api.revival.capabilities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;