@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package jakojaannos.life.entity.capability;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;