@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package jakojaannos.life.revival.capability;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;